spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/imobi
        username: postgres
        password: 1234
    jpa:
        hibernate:
            ddlAuto: update
        showSql: true
    redis:
        host: localhost
        port: 6379
    cache:
        type: redis
        redis:
            time-to-live: 20_000